name: CI Build Scan Push

on:
  push:
    branches: [ "master" ]
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  build-scan-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install deps
        working-directory: app/backend
        run: npm ci

      - name: Run tests (placeholder)
        working-directory: app/backend
        run: npm test --if-present || true

      - name: Build image
        run: |
          docker build \
            -f ./docker/backend.dockerfile \
            -t ghcr.io/${{ github.repository_owner }}/devops-backend:${{ github.sha }} \
            -t ghcr.io/${{ github.repository_owner }}/devops-backend:latest \
            .
            

      - name: Trivy scan OS (gate)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ghcr.io/${{ github.repository_owner }}/devops-backend:${{ github.sha }}
          format: table
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: os
          severity: CRITICAL,HIGH

      - name: Trivy scan libraries (report only)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ghcr.io/${{ github.repository_owner }}/devops-backend:${{ github.sha }}
          format: table
          exit-code: "0"
          ignore-unfixed: true
          vuln-type: library
          severity: CRITICAL,HIGH

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/devops-backend:${{ github.sha }}
          docker push ghcr.io/${{ github.repository_owner }}/devops-backend:latest
